export function createComparison(){
 const box=document.createElement('section');box.style.cssText='padding:16px;border:1px solid #547c6b;margin:20px 0';
 box.innerHTML='<h2>一次对比：投影是否影响手部识别</h2><p>保持相机不动，两次都把同一只手放在同一位置。先用投影仪的息屏/遮屏功能关闭投影光，再恢复投影。网页无法自动确认投影仪状态。每段8秒，自动保存数值，不保存视频。</p><button id="compare-start">投影已关闭，开始8秒记录</button> <button id="compare-stop" disabled>中止并保存</button><p id="compare-status" role="status">不用校准空墙也可以比较手部识别。</p><div id="compare-report"></div><details><summary>已保存的对比记录</summary><div id="compare-history"></div></details>';
 document.querySelector('main').append(box);
 const button=box.querySelector('#compare-start'),stop=box.querySelector('#compare-stop'),status=box.querySelector('#compare-status');
 let id=null,step=0,running=false,busy=false,until=0,latest=null,at=0;
 async function api(action,data={}){const r=await fetch('/api/compare/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...data}),signal:AbortSignal.timeout(4000)});const j=await r.json();if(!r.ok)throw Error(j.error);return j}
 function report(r){const result=box.querySelector('#compare-report');result.replaceChildren();for(const s of r.steps){const p=document.createElement('p');p.textContent=`${s.name}：${s.samples}次采样，${s.hand_frames}次识别完整手部，${s.invalid_frames}次数据异常。${s.completed?'已记录':'未完成'}`;result.append(p)}const p=document.createElement('p');p.textContent='这只能对比识别表现；动作、摆放和光线也会影响结果，不能单凭比例证明原因。';result.append(p);const a=document.createElement('a');a.textContent='完整数值报告（本机）';a.href='/api/comparisons/'+r.id;a.target='_blank';result.append(a)}
 async function history(){try{const r=await fetch('/api/comparisons');const rows=await r.json();const list=box.querySelector('#compare-history');list.replaceChildren();for(const row of rows){const b=document.createElement('button');b.textContent=row.status+' '+row.id.slice(0,8);b.onclick=async()=>{try{const res=await fetch('/api/comparisons/'+row.id);report(await res.json())}catch(e){status.textContent=e.message}};list.append(b)}}catch{}}
 async function finish(complete){const r=await api('finish',{complete});report(r);id=null;step=0;running=false;button.disabled=false;stop.disabled=true;button.textContent='开始新的投影关闭／开启对比';status.textContent='记录已保存到本机 reports/vision。';await history()}
 button.onclick=async()=>{if(busy||running)return;if(!latest?.usable||performance.now()-at>700){status.textContent='请先等待相机画面和识别模型就绪';return}busy=true;button.disabled=true;try{if(!id){id=(await api('start')).id;step=0}await api('step',{step});until=performance.now()+8000;running=true;stop.disabled=false}catch(e){status.textContent='无法开始：'+e.message;button.disabled=false}finally{busy=false}};
 stop.onclick=async()=>{if(busy)return;busy=true;running=false;try{await finish(false)}catch(e){status.textContent='保存失败：'+e.message}finally{busy=false}};
 async function tick(){if(running&&!busy){busy=true;try{const s=latest&&performance.now()-at<700?latest:{usable:false,joints:[],mm:null,active:false,reason:'画面中断'};await api('sample',s);status.textContent=`${step===0?'投影关闭':'投影开启'}：正在保存，剩余${Math.max(0,Math.ceil((until-performance.now())/1000))}秒`;if(performance.now()>=until){await api('end');running=false;if(step===0){step=1;button.disabled=false;button.textContent='投影已开启，记录第二段8秒';status.textContent='第一段已保存。恢复投影光，把手放回同一位置，再点击第二段。'}else await finish(true)}}catch(e){running=false;status.textContent='记录中断：'+e.message+'。已写入数据保留，请中止保存。'}finally{busy=false}}setTimeout(tick,150)}
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){running=false;status.textContent='页面被隐藏，已暂停。请中止保存后重新开始，避免把浏览器暂停误判为识别失败。'}});
 void history();void tick();
 return sample=>{latest=sample;at=performance.now()};
}
